### ISSUE TITLE
Error with example code

### ISSUE THREAD

**Issue by piranna** [maxmind/MaxMind-DB-Writer-perl#89] opened 2017-07-24 17:40 UTC
I've installed the writer from CPAN, and when running the example code from the readme I've got the next error:

```
Iteration is not currently allowed in trees with no nodes. Record type: empty at /usr/local/lib/x86_64-linux-gnu/perl/5.24.1/MaxMind/DB/Writer/Tree.pm line 292.
```

I'm mostly new to Perl and totally new to CPAN. Any suggestion about what can I do?

**Comment by oschwald** [comment] 2017-07-24 17:44
Thanks for bringing this up. The issue is that the network in the example, `2001:db8::/48` is a reserved network, which are removed by default. If you replace it with something like `2003:db8::/48`, it will work. If you don't want reserved networks removed from the tree, you can add `remove_reserved_networks => 1` to the constructor call.

**Comment by piranna** [comment] 2017-07-24 17:54
> If you replace it with something like 2003:db8::/48, it will work.

In fact, it worked! :-D


> If you don't want reserved networks removed from the tree, you can add remove_reserved_networks => 0 to the constructor call.

Are you taking about the constructor of `MaxMind::DB::Writer::Tree->new`?

By the way, I'm not sure if this should be put on the readme, I got frightened when saw it was not working... :-/

**Comment by oschwald** [comment] 2017-07-24 18:10
> Are you taking about the constructor of MaxMind::DB::Writer::Tree->new?

Yes.

> By the way, I'm not sure if this should be put on the readme, I got frightened when saw it was not working... :-/

Yeah, the documentation should be fixed. I'll leave this open until we fix it.

**Comment by piranna** [comment] 2017-07-24 18:17
> Yeah, the documentation should be fixed. I'll leave this open until we fix it.

Ok, cool! :-)

**Closed** 2017-11-10 21:51 UTC
